# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: "Syed Zaidi – Curriculum Vitae"
first_name: "Syed"
middle_name: ""
last_name: "Zaidi"
contact_note: >
  The best way to reach me is via email.
description: >
  An academic website showcasing my CV, research, teaching, and industry experience.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with the <a href="https://github.com/alshedivat/al-folio" target="_blank">al‑folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
  Photos from <a href="https://unsplash.com/" target="_blank">Unsplash</a>.
keywords: jekyll, jekyll-theme, academic-website, CV, portfolio
lang: en
icon: ⚛️

# Use your own domain or GitHub Pages URL – for a personal site hosted at
# https://zaidisyed1991.github.io, set baseurl to empty.
url: "https://zaidisyed1991.github.io"  
baseurl: ""  
last_updated: true
impressum_path:
back_to_top: true

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------
repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------
rss_icon: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------
navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: true
posts_in_search: true
bib_search: true
max_width: 930px

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------
serve_og_meta: true
serve_schema_org: false
og_image: "/assets/img/og-image.jpg"

# -----------------------------------------------------------------------------
# Analytics and verification (update if needed)
# -----------------------------------------------------------------------------
google_analytics:
cronitor_analytics:
pirsch_analytics:
openpanel_analytics:
google_site_verification:
bing_site_verification:

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: "My Academic Blog"
blog_description: "A simple academic portfolio and blog"
permalink: /blog/:year/:title/
lsi: false

pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related: 5

# -----------------------------------------------------------------------------
# Comments (Giscus recommended)
# -----------------------------------------------------------------------------
giscus:
  repo: "zaidisyed1991/zaidisyed1991.github.io"
  repo_id: ""
  category: "Comments"
  category_id: ""
  mapping: title
  strict: 1
  reactions_enabled: 1
  input_position: bottom
  theme: preferred_color_scheme
  emit_metadata: 0
  lang: en

disqus_shortname: "zaidisyed1991"

external_sources:
  - name: medium.com
    rss_url: "https://medium.com/@zaidisyed1991/feed"

# -----------------------------------------------------------------------------
# Newsletter
# -----------------------------------------------------------------------------
newsletter:
  enabled: false
  endpoint:

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  books:
    output: true
  news:
    defaults:
      layout: post
    output: true
  projects:
    output: true

# -----------------------------------------------------------------------------
# Jekyll settings & Plugins
# -----------------------------------------------------------------------------
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: ["_pages", "_scripts"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - purgecss.config.js
  - README.md
  - readme_preview/
  - vendor
keep_files:
  - CNAME
  - .nojekyll

plugins:
  - jekyll-archives-v2
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-tabs
  - jekyll-terser
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

jekyll-minifier:
  compress_javascript: false
  exclude: ["robots.txt", "assets/js/search/*.js"]

terser:
  compress:
    drop_console: true

jekyll-archives:
  posts:
    enabled: [year, tags, categories]
    permalinks:
      year: "/blog/:year/"
      tags: "/blog/:type/:name/"
      categories: "/blog/:type/:name/"
  books:
    enabled: [year, tags, categories]

display_tags: ["formatting", "images", "links", "math", "code", "blockquotes"]
display_categories: ["external-services"]

# -----------------------------------------------------------------------------
# Jekyll Scholar (for publications)
# -----------------------------------------------------------------------------
scholar:
  last_name: [Zaidi]
  first_name: [Syed]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters: [latex, smallcaps, superscript]
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_link: Details
  query: "@*"
  group_by: year
  group_order: descending

enable_publication_badges:
  altmetric: true
  dimensions: true
  google_scholar: true
  inspirehep: true

filtered_bibtex_keywords:
  - abbr
  - abstract
  - additional_info
  - altmetric
  - annotation
  - arxiv
  - award
  - award_name
  - bibtex_show
  - blog
  - code
  - google_scholar_id
  - html
  - inspirehep_id
  - pdf
  - poster
  - preview
  - selected
  - slides
  - supp
  - video
  - website

max_author_limit: 3
more_authors_animation_delay: 10

enable_publication_thumbnails: true

external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank

imagemagick:
  enabled: true
  widths: [480, 800, 1400]
  input_directories: ["assets/img/"]
  input_formats: [".jpg", ".jpeg", ".png", ".tiff", ".gif"]
  output_formats:
    webp: "-quality 85"

lazy_loading_images: true

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------
enable_google_analytics: false
enable_cronitor_analytics: false
enable_pirsch_analytics: false
enable_openpanel_analytics: false
enable_google_verification: false
enable_bing_verification: false
enable_masonry: true
enable_math: true
enable_tooltips: false
enable_darkmode: true
enable_navbar_social: false
enable_project_categories: true
enable_medium_zoom: true
enable_progressbar: true
enable_video_embedding: false

third_party_libraries:
  download: false

jekyll_get_json:
  - data: resume
    json: assets/json/resume.json

jsonresume:
  - basics
  - work
  - education
  - publications
  - projects
  - volunteer
  - awards
  - certificates
  - skills
  - languages
  - interests
  - references
